# Generated by Django 3.2.6 on 2021-08-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210827_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='aquariums',
            field=models.ManyToManyField(to='main_app.Aquarium'),
        ),
    ]
